version: '3'
services:
  app:
    build:
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - HUBOT_NAME=mmbot
        - HUBOT_OWNER=none
        - HUBOT_DESCRIPTION=Hubot with matteruser adapter
      context: .
    environment:
      - MATTERMOST_HOST=192.168.99.100
      - MATTERMOST_GROUP=mmtest1
      - MATTERMOST_USER=hubottest@example.jp
      - MATTERMOST_PASSWORD=hubottest
      - MATTERMOST_WSS_PORT=80
      - MATTERMOST_TLS_VERIFY=false
      - MATTERMOST_USE_TLS=false
      - HUBOT_JENKINS_URL=http://192.168.99.100:50001
      - HUBOT_JENKINS_AUTH=admin:admin
      - TZ=Asia/Tokyo
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/home/hubot
volumes:
  data: {}
