version: '3'
services:
  app:
    build:
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - HUBOT_NAME=mmbot
        - HUBOT_OWNER=none
        - HUBOT_DESCRIPTION=Hubot with matteruser adapter
      context: .
    environment:
      - MATTERMOST_HOST=${MATTERMOST_HOST}
      - MATTERMOST_GROUP=${MATTERMOST_GROUP}
      - MATTERMOST_USER=${MATTERMOST_USER}
      - MATTERMOST_PASSWORD=${MATTERMOST_PASSWORD}
      - MATTERMOST_HTTP_PORT=${MATTERMOST_HTTP_PORT}
      - MATTERMOST_WSS_PORT=${MATTERMOST_WSS_PORT}
      - MATTERMOST_TLS_VERIFY=${MATTERMOST_TLS_VERIFY}
      - MATTERMOST_USE_TLS=${MATTERMOST_USE_TLS}
      - HUBOT_JENKINS_URL=${HUBOT_JENKINS_URL}
      - HUBOT_JENKINS_AUTH=${HUBOT_JENKINS_AUTH}
      - TZ=Asia/Tokyo
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/home/hubot
volumes:
  data: {}
